package com.xzgl.www.entity;

import java.util.ArrayList;
import java.util.List;

public class DealinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public DealinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHandleidIsNull() {
            addCriterion("HandleID is null");
            return (Criteria) this;
        }

        public Criteria andHandleidIsNotNull() {
            addCriterion("HandleID is not null");
            return (Criteria) this;
        }

        public Criteria andHandleidEqualTo(String value) {
            addCriterion("HandleID =", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidNotEqualTo(String value) {
            addCriterion("HandleID <>", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidGreaterThan(String value) {
            addCriterion("HandleID >", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidGreaterThanOrEqualTo(String value) {
            addCriterion("HandleID >=", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidLessThan(String value) {
            addCriterion("HandleID <", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidLessThanOrEqualTo(String value) {
            addCriterion("HandleID <=", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidLike(String value) {
            addCriterion("HandleID like", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidNotLike(String value) {
            addCriterion("HandleID not like", value, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidIn(List<String> values) {
            addCriterion("HandleID in", values, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidNotIn(List<String> values) {
            addCriterion("HandleID not in", values, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidBetween(String value1, String value2) {
            addCriterion("HandleID between", value1, value2, "handleid");
            return (Criteria) this;
        }

        public Criteria andHandleidNotBetween(String value1, String value2) {
            addCriterion("HandleID not between", value1, value2, "handleid");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNull() {
            addCriterion("CaseNumber is null");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNotNull() {
            addCriterion("CaseNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCasenumberEqualTo(String value) {
            addCriterion("CaseNumber =", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotEqualTo(String value) {
            addCriterion("CaseNumber <>", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThan(String value) {
            addCriterion("CaseNumber >", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThanOrEqualTo(String value) {
            addCriterion("CaseNumber >=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThan(String value) {
            addCriterion("CaseNumber <", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThanOrEqualTo(String value) {
            addCriterion("CaseNumber <=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLike(String value) {
            addCriterion("CaseNumber like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotLike(String value) {
            addCriterion("CaseNumber not like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIn(List<String> values) {
            addCriterion("CaseNumber in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotIn(List<String> values) {
            addCriterion("CaseNumber not in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberBetween(String value1, String value2) {
            addCriterion("CaseNumber between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotBetween(String value1, String value2) {
            addCriterion("CaseNumber not between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andAdepartmentIsNull() {
            addCriterion("Adepartment is null");
            return (Criteria) this;
        }

        public Criteria andAdepartmentIsNotNull() {
            addCriterion("Adepartment is not null");
            return (Criteria) this;
        }

        public Criteria andAdepartmentEqualTo(String value) {
            addCriterion("Adepartment =", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentNotEqualTo(String value) {
            addCriterion("Adepartment <>", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentGreaterThan(String value) {
            addCriterion("Adepartment >", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("Adepartment >=", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentLessThan(String value) {
            addCriterion("Adepartment <", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentLessThanOrEqualTo(String value) {
            addCriterion("Adepartment <=", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentLike(String value) {
            addCriterion("Adepartment like", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentNotLike(String value) {
            addCriterion("Adepartment not like", value, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentIn(List<String> values) {
            addCriterion("Adepartment in", values, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentNotIn(List<String> values) {
            addCriterion("Adepartment not in", values, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentBetween(String value1, String value2) {
            addCriterion("Adepartment between", value1, value2, "adepartment");
            return (Criteria) this;
        }

        public Criteria andAdepartmentNotBetween(String value1, String value2) {
            addCriterion("Adepartment not between", value1, value2, "adepartment");
            return (Criteria) this;
        }

        public Criteria andStepsIsNull() {
            addCriterion("Steps is null");
            return (Criteria) this;
        }

        public Criteria andStepsIsNotNull() {
            addCriterion("Steps is not null");
            return (Criteria) this;
        }

        public Criteria andStepsEqualTo(String value) {
            addCriterion("Steps =", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotEqualTo(String value) {
            addCriterion("Steps <>", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsGreaterThan(String value) {
            addCriterion("Steps >", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsGreaterThanOrEqualTo(String value) {
            addCriterion("Steps >=", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsLessThan(String value) {
            addCriterion("Steps <", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsLessThanOrEqualTo(String value) {
            addCriterion("Steps <=", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsLike(String value) {
            addCriterion("Steps like", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotLike(String value) {
            addCriterion("Steps not like", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsIn(List<String> values) {
            addCriterion("Steps in", values, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotIn(List<String> values) {
            addCriterion("Steps not in", values, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsBetween(String value1, String value2) {
            addCriterion("Steps between", value1, value2, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotBetween(String value1, String value2) {
            addCriterion("Steps not between", value1, value2, "steps");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dealinfo
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 06 22:59:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dealinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}