package com.xzgl.www.entity;

import java.util.Date;

public class Fileinfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.Fileid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.FileOname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String fileoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.FileNname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String filenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.FileEname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String fileename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.Filetime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private Date filetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.type
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfos.id
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.Fileid
     *
     * @return the value of fileinfos.Fileid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.Fileid
     *
     * @param fileid the value for fileinfos.Fileid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.FileOname
     *
     * @return the value of fileinfos.FileOname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getFileoname() {
        return fileoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.FileOname
     *
     * @param fileoname the value for fileinfos.FileOname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFileoname(String fileoname) {
        this.fileoname = fileoname == null ? null : fileoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.FileNname
     *
     * @return the value of fileinfos.FileNname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getFilenname() {
        return filenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.FileNname
     *
     * @param filenname the value for fileinfos.FileNname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFilenname(String filenname) {
        this.filenname = filenname == null ? null : filenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.FileEname
     *
     * @return the value of fileinfos.FileEname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getFileename() {
        return fileename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.FileEname
     *
     * @param fileename the value for fileinfos.FileEname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFileename(String fileename) {
        this.fileename = fileename == null ? null : fileename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.Filetime
     *
     * @return the value of fileinfos.Filetime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Date getFiletime() {
        return filetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.Filetime
     *
     * @param filetime the value for fileinfos.Filetime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFiletime(Date filetime) {
        this.filetime = filetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.type
     *
     * @return the value of fileinfos.type
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.type
     *
     * @param type the value for fileinfos.type
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfos.id
     *
     * @return the value of fileinfos.id
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfos.id
     *
     * @param id the value for fileinfos.id
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}