package com.xzgl.www.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordinformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public RecordinformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCasenumberIsNull() {
            addCriterion("CaseNumber is null");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNotNull() {
            addCriterion("CaseNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCasenumberEqualTo(String value) {
            addCriterion("CaseNumber =", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotEqualTo(String value) {
            addCriterion("CaseNumber <>", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThan(String value) {
            addCriterion("CaseNumber >", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThanOrEqualTo(String value) {
            addCriterion("CaseNumber >=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThan(String value) {
            addCriterion("CaseNumber <", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThanOrEqualTo(String value) {
            addCriterion("CaseNumber <=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLike(String value) {
            addCriterion("CaseNumber like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotLike(String value) {
            addCriterion("CaseNumber not like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIn(List<String> values) {
            addCriterion("CaseNumber in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotIn(List<String> values) {
            addCriterion("CaseNumber not in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberBetween(String value1, String value2) {
            addCriterion("CaseNumber between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotBetween(String value1, String value2) {
            addCriterion("CaseNumber not between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("Userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("Userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("Userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("Userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("Userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("Userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("Userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("Userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("Userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("Userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("Userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("Userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("Userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("Userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCasetitleIsNull() {
            addCriterion("Casetitle is null");
            return (Criteria) this;
        }

        public Criteria andCasetitleIsNotNull() {
            addCriterion("Casetitle is not null");
            return (Criteria) this;
        }

        public Criteria andCasetitleEqualTo(String value) {
            addCriterion("Casetitle =", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleNotEqualTo(String value) {
            addCriterion("Casetitle <>", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleGreaterThan(String value) {
            addCriterion("Casetitle >", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleGreaterThanOrEqualTo(String value) {
            addCriterion("Casetitle >=", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleLessThan(String value) {
            addCriterion("Casetitle <", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleLessThanOrEqualTo(String value) {
            addCriterion("Casetitle <=", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleLike(String value) {
            addCriterion("Casetitle like", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleNotLike(String value) {
            addCriterion("Casetitle not like", value, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleIn(List<String> values) {
            addCriterion("Casetitle in", values, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleNotIn(List<String> values) {
            addCriterion("Casetitle not in", values, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleBetween(String value1, String value2) {
            addCriterion("Casetitle between", value1, value2, "casetitle");
            return (Criteria) this;
        }

        public Criteria andCasetitleNotBetween(String value1, String value2) {
            addCriterion("Casetitle not between", value1, value2, "casetitle");
            return (Criteria) this;
        }

        public Criteria andPartiesIsNull() {
            addCriterion("Parties is null");
            return (Criteria) this;
        }

        public Criteria andPartiesIsNotNull() {
            addCriterion("Parties is not null");
            return (Criteria) this;
        }

        public Criteria andPartiesEqualTo(String value) {
            addCriterion("Parties =", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesNotEqualTo(String value) {
            addCriterion("Parties <>", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesGreaterThan(String value) {
            addCriterion("Parties >", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesGreaterThanOrEqualTo(String value) {
            addCriterion("Parties >=", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesLessThan(String value) {
            addCriterion("Parties <", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesLessThanOrEqualTo(String value) {
            addCriterion("Parties <=", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesLike(String value) {
            addCriterion("Parties like", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesNotLike(String value) {
            addCriterion("Parties not like", value, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesIn(List<String> values) {
            addCriterion("Parties in", values, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesNotIn(List<String> values) {
            addCriterion("Parties not in", values, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesBetween(String value1, String value2) {
            addCriterion("Parties between", value1, value2, "parties");
            return (Criteria) this;
        }

        public Criteria andPartiesNotBetween(String value1, String value2) {
            addCriterion("Parties not between", value1, value2, "parties");
            return (Criteria) this;
        }

        public Criteria andCasesourceIsNull() {
            addCriterion("Casesource is null");
            return (Criteria) this;
        }

        public Criteria andCasesourceIsNotNull() {
            addCriterion("Casesource is not null");
            return (Criteria) this;
        }

        public Criteria andCasesourceEqualTo(String value) {
            addCriterion("Casesource =", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceNotEqualTo(String value) {
            addCriterion("Casesource <>", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceGreaterThan(String value) {
            addCriterion("Casesource >", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceGreaterThanOrEqualTo(String value) {
            addCriterion("Casesource >=", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceLessThan(String value) {
            addCriterion("Casesource <", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceLessThanOrEqualTo(String value) {
            addCriterion("Casesource <=", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceLike(String value) {
            addCriterion("Casesource like", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceNotLike(String value) {
            addCriterion("Casesource not like", value, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceIn(List<String> values) {
            addCriterion("Casesource in", values, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceNotIn(List<String> values) {
            addCriterion("Casesource not in", values, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceBetween(String value1, String value2) {
            addCriterion("Casesource between", value1, value2, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasesourceNotBetween(String value1, String value2) {
            addCriterion("Casesource not between", value1, value2, "casesource");
            return (Criteria) this;
        }

        public Criteria andCasenameIsNull() {
            addCriterion("Casename is null");
            return (Criteria) this;
        }

        public Criteria andCasenameIsNotNull() {
            addCriterion("Casename is not null");
            return (Criteria) this;
        }

        public Criteria andCasenameEqualTo(String value) {
            addCriterion("Casename =", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameNotEqualTo(String value) {
            addCriterion("Casename <>", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameGreaterThan(String value) {
            addCriterion("Casename >", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameGreaterThanOrEqualTo(String value) {
            addCriterion("Casename >=", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameLessThan(String value) {
            addCriterion("Casename <", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameLessThanOrEqualTo(String value) {
            addCriterion("Casename <=", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameLike(String value) {
            addCriterion("Casename like", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameNotLike(String value) {
            addCriterion("Casename not like", value, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameIn(List<String> values) {
            addCriterion("Casename in", values, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameNotIn(List<String> values) {
            addCriterion("Casename not in", values, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameBetween(String value1, String value2) {
            addCriterion("Casename between", value1, value2, "casename");
            return (Criteria) this;
        }

        public Criteria andCasenameNotBetween(String value1, String value2) {
            addCriterion("Casename not between", value1, value2, "casename");
            return (Criteria) this;
        }

        public Criteria andRecordtimeIsNull() {
            addCriterion("Recordtime is null");
            return (Criteria) this;
        }

        public Criteria andRecordtimeIsNotNull() {
            addCriterion("Recordtime is not null");
            return (Criteria) this;
        }

        public Criteria andRecordtimeEqualTo(Date value) {
            addCriterion("Recordtime =", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeNotEqualTo(Date value) {
            addCriterion("Recordtime <>", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeGreaterThan(Date value) {
            addCriterion("Recordtime >", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Recordtime >=", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeLessThan(Date value) {
            addCriterion("Recordtime <", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeLessThanOrEqualTo(Date value) {
            addCriterion("Recordtime <=", value, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeIn(List<Date> values) {
            addCriterion("Recordtime in", values, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeNotIn(List<Date> values) {
            addCriterion("Recordtime not in", values, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeBetween(Date value1, Date value2) {
            addCriterion("Recordtime between", value1, value2, "recordtime");
            return (Criteria) this;
        }

        public Criteria andRecordtimeNotBetween(Date value1, Date value2) {
            addCriterion("Recordtime not between", value1, value2, "recordtime");
            return (Criteria) this;
        }

        public Criteria andCrimereportsIsNull() {
            addCriterion("Crimereports is null");
            return (Criteria) this;
        }

        public Criteria andCrimereportsIsNotNull() {
            addCriterion("Crimereports is not null");
            return (Criteria) this;
        }

        public Criteria andCrimereportsEqualTo(String value) {
            addCriterion("Crimereports =", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsNotEqualTo(String value) {
            addCriterion("Crimereports <>", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsGreaterThan(String value) {
            addCriterion("Crimereports >", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsGreaterThanOrEqualTo(String value) {
            addCriterion("Crimereports >=", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsLessThan(String value) {
            addCriterion("Crimereports <", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsLessThanOrEqualTo(String value) {
            addCriterion("Crimereports <=", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsLike(String value) {
            addCriterion("Crimereports like", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsNotLike(String value) {
            addCriterion("Crimereports not like", value, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsIn(List<String> values) {
            addCriterion("Crimereports in", values, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsNotIn(List<String> values) {
            addCriterion("Crimereports not in", values, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsBetween(String value1, String value2) {
            addCriterion("Crimereports between", value1, value2, "crimereports");
            return (Criteria) this;
        }

        public Criteria andCrimereportsNotBetween(String value1, String value2) {
            addCriterion("Crimereports not between", value1, value2, "crimereports");
            return (Criteria) this;
        }

        public Criteria andAccordingIsNull() {
            addCriterion("According is null");
            return (Criteria) this;
        }

        public Criteria andAccordingIsNotNull() {
            addCriterion("According is not null");
            return (Criteria) this;
        }

        public Criteria andAccordingEqualTo(String value) {
            addCriterion("According =", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingNotEqualTo(String value) {
            addCriterion("According <>", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingGreaterThan(String value) {
            addCriterion("According >", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingGreaterThanOrEqualTo(String value) {
            addCriterion("According >=", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingLessThan(String value) {
            addCriterion("According <", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingLessThanOrEqualTo(String value) {
            addCriterion("According <=", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingLike(String value) {
            addCriterion("According like", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingNotLike(String value) {
            addCriterion("According not like", value, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingIn(List<String> values) {
            addCriterion("According in", values, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingNotIn(List<String> values) {
            addCriterion("According not in", values, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingBetween(String value1, String value2) {
            addCriterion("According between", value1, value2, "according");
            return (Criteria) this;
        }

        public Criteria andAccordingNotBetween(String value1, String value2) {
            addCriterion("According not between", value1, value2, "according");
            return (Criteria) this;
        }

        public Criteria andFileuploadIsNull() {
            addCriterion("Fileupload is null");
            return (Criteria) this;
        }

        public Criteria andFileuploadIsNotNull() {
            addCriterion("Fileupload is not null");
            return (Criteria) this;
        }

        public Criteria andFileuploadEqualTo(String value) {
            addCriterion("Fileupload =", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadNotEqualTo(String value) {
            addCriterion("Fileupload <>", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadGreaterThan(String value) {
            addCriterion("Fileupload >", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadGreaterThanOrEqualTo(String value) {
            addCriterion("Fileupload >=", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadLessThan(String value) {
            addCriterion("Fileupload <", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadLessThanOrEqualTo(String value) {
            addCriterion("Fileupload <=", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadLike(String value) {
            addCriterion("Fileupload like", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadNotLike(String value) {
            addCriterion("Fileupload not like", value, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadIn(List<String> values) {
            addCriterion("Fileupload in", values, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadNotIn(List<String> values) {
            addCriterion("Fileupload not in", values, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadBetween(String value1, String value2) {
            addCriterion("Fileupload between", value1, value2, "fileupload");
            return (Criteria) this;
        }

        public Criteria andFileuploadNotBetween(String value1, String value2) {
            addCriterion("Fileupload not between", value1, value2, "fileupload");
            return (Criteria) this;
        }

        public Criteria andCasemoldIsNull() {
            addCriterion("Casemold is null");
            return (Criteria) this;
        }

        public Criteria andCasemoldIsNotNull() {
            addCriterion("Casemold is not null");
            return (Criteria) this;
        }

        public Criteria andCasemoldEqualTo(String value) {
            addCriterion("Casemold =", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldNotEqualTo(String value) {
            addCriterion("Casemold <>", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldGreaterThan(String value) {
            addCriterion("Casemold >", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldGreaterThanOrEqualTo(String value) {
            addCriterion("Casemold >=", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldLessThan(String value) {
            addCriterion("Casemold <", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldLessThanOrEqualTo(String value) {
            addCriterion("Casemold <=", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldLike(String value) {
            addCriterion("Casemold like", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldNotLike(String value) {
            addCriterion("Casemold not like", value, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldIn(List<String> values) {
            addCriterion("Casemold in", values, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldNotIn(List<String> values) {
            addCriterion("Casemold not in", values, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldBetween(String value1, String value2) {
            addCriterion("Casemold between", value1, value2, "casemold");
            return (Criteria) this;
        }

        public Criteria andCasemoldNotBetween(String value1, String value2) {
            addCriterion("Casemold not between", value1, value2, "casemold");
            return (Criteria) this;
        }

        public Criteria andCutnumberIsNull() {
            addCriterion("Cutnumber is null");
            return (Criteria) this;
        }

        public Criteria andCutnumberIsNotNull() {
            addCriterion("Cutnumber is not null");
            return (Criteria) this;
        }

        public Criteria andCutnumberEqualTo(String value) {
            addCriterion("Cutnumber =", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberNotEqualTo(String value) {
            addCriterion("Cutnumber <>", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberGreaterThan(String value) {
            addCriterion("Cutnumber >", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberGreaterThanOrEqualTo(String value) {
            addCriterion("Cutnumber >=", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberLessThan(String value) {
            addCriterion("Cutnumber <", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberLessThanOrEqualTo(String value) {
            addCriterion("Cutnumber <=", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberLike(String value) {
            addCriterion("Cutnumber like", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberNotLike(String value) {
            addCriterion("Cutnumber not like", value, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberIn(List<String> values) {
            addCriterion("Cutnumber in", values, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberNotIn(List<String> values) {
            addCriterion("Cutnumber not in", values, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberBetween(String value1, String value2) {
            addCriterion("Cutnumber between", value1, value2, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andCutnumberNotBetween(String value1, String value2) {
            addCriterion("Cutnumber not between", value1, value2, "cutnumber");
            return (Criteria) this;
        }

        public Criteria andDpnoIsNull() {
            addCriterion("DpNo is null");
            return (Criteria) this;
        }

        public Criteria andDpnoIsNotNull() {
            addCriterion("DpNo is not null");
            return (Criteria) this;
        }

        public Criteria andDpnoEqualTo(String value) {
            addCriterion("DpNo =", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoNotEqualTo(String value) {
            addCriterion("DpNo <>", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoGreaterThan(String value) {
            addCriterion("DpNo >", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoGreaterThanOrEqualTo(String value) {
            addCriterion("DpNo >=", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoLessThan(String value) {
            addCriterion("DpNo <", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoLessThanOrEqualTo(String value) {
            addCriterion("DpNo <=", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoLike(String value) {
            addCriterion("DpNo like", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoNotLike(String value) {
            addCriterion("DpNo not like", value, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoIn(List<String> values) {
            addCriterion("DpNo in", values, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoNotIn(List<String> values) {
            addCriterion("DpNo not in", values, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoBetween(String value1, String value2) {
            addCriterion("DpNo between", value1, value2, "dpno");
            return (Criteria) this;
        }

        public Criteria andDpnoNotBetween(String value1, String value2) {
            addCriterion("DpNo not between", value1, value2, "dpno");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisIsNull() {
            addCriterion("CurrentstaUis is null");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisIsNotNull() {
            addCriterion("CurrentstaUis is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisEqualTo(String value) {
            addCriterion("CurrentstaUis =", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisNotEqualTo(String value) {
            addCriterion("CurrentstaUis <>", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisGreaterThan(String value) {
            addCriterion("CurrentstaUis >", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisGreaterThanOrEqualTo(String value) {
            addCriterion("CurrentstaUis >=", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisLessThan(String value) {
            addCriterion("CurrentstaUis <", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisLessThanOrEqualTo(String value) {
            addCriterion("CurrentstaUis <=", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisLike(String value) {
            addCriterion("CurrentstaUis like", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisNotLike(String value) {
            addCriterion("CurrentstaUis not like", value, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisIn(List<String> values) {
            addCriterion("CurrentstaUis in", values, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisNotIn(List<String> values) {
            addCriterion("CurrentstaUis not in", values, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisBetween(String value1, String value2) {
            addCriterion("CurrentstaUis between", value1, value2, "currentstauis");
            return (Criteria) this;
        }

        public Criteria andCurrentstauisNotBetween(String value1, String value2) {
            addCriterion("CurrentstaUis not between", value1, value2, "currentstauis");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recordinformation
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 06 22:59:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}