package com.xzgl.www.entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Roleid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String dpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.LevelNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String levelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Password
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.CPassword
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Email
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.People
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Cellphone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Mobilephone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.IDCardNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String idcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Usrname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String usrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Address
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Phone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.beizhu
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Userid
     *
     * @return the value of userinfo.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Userid
     *
     * @param userid the value for userinfo.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Roleid
     *
     * @return the value of userinfo.Roleid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Roleid
     *
     * @param roleid the value for userinfo.Roleid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.DpNo
     *
     * @return the value of userinfo.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getDpno() {
        return dpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.DpNo
     *
     * @param dpno the value for userinfo.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDpno(String dpno) {
        this.dpno = dpno == null ? null : dpno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.LevelNo
     *
     * @return the value of userinfo.LevelNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getLevelno() {
        return levelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.LevelNo
     *
     * @param levelno the value for userinfo.LevelNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setLevelno(String levelno) {
        this.levelno = levelno == null ? null : levelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Password
     *
     * @return the value of userinfo.Password
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Password
     *
     * @param password the value for userinfo.Password
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.CPassword
     *
     * @return the value of userinfo.CPassword
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCpassword() {
        return cpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.CPassword
     *
     * @param cpassword the value for userinfo.CPassword
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCpassword(String cpassword) {
        this.cpassword = cpassword == null ? null : cpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Email
     *
     * @return the value of userinfo.Email
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Email
     *
     * @param email the value for userinfo.Email
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.People
     *
     * @return the value of userinfo.People
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.People
     *
     * @param people the value for userinfo.People
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setPeople(String people) {
        this.people = people == null ? null : people.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Cellphone
     *
     * @return the value of userinfo.Cellphone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Cellphone
     *
     * @param cellphone the value for userinfo.Cellphone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Mobilephone
     *
     * @return the value of userinfo.Mobilephone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Mobilephone
     *
     * @param mobilephone the value for userinfo.Mobilephone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.IDCardNo
     *
     * @return the value of userinfo.IDCardNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getIdcardno() {
        return idcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.IDCardNo
     *
     * @param idcardno the value for userinfo.IDCardNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setIdcardno(String idcardno) {
        this.idcardno = idcardno == null ? null : idcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Usrname
     *
     * @return the value of userinfo.Usrname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getUsrname() {
        return usrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Usrname
     *
     * @param usrname the value for userinfo.Usrname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setUsrname(String usrname) {
        this.usrname = usrname == null ? null : usrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Address
     *
     * @return the value of userinfo.Address
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Address
     *
     * @param address the value for userinfo.Address
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Phone
     *
     * @return the value of userinfo.Phone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Phone
     *
     * @param phone the value for userinfo.Phone
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Department
     *
     * @return the value of userinfo.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Department
     *
     * @param department the value for userinfo.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.beizhu
     *
     * @return the value of userinfo.beizhu
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.beizhu
     *
     * @param beizhu the value for userinfo.beizhu
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}