package com.giit.www.mapper;

import com.giit.www.entity.BussinessInfo;
import com.giit.www.entity.BussinessInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BussinessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int countByExample(BussinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int deleteByExample(BussinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int deleteByPrimaryKey(String bunumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int insert(BussinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int insertSelective(BussinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    List<BussinessInfo> selectByExample(BussinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    BussinessInfo selectByPrimaryKey(String bunumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") BussinessInfo record, @Param("example") BussinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int updateByExample(@Param("record") BussinessInfo record, @Param("example") BussinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int updateByPrimaryKeySelective(BussinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bussiness_info
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    int updateByPrimaryKey(BussinessInfo record);
}