package com.giit.www.mapper;

import com.giit.www.entity.Departmentinfo;
import com.giit.www.entity.DepartmentinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int countByExample(DepartmentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int deleteByExample(DepartmentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int deleteByPrimaryKey(String dpno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int insert(Departmentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int insertSelective(Departmentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    List<Departmentinfo> selectByExample(DepartmentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    Departmentinfo selectByPrimaryKey(String dpno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") Departmentinfo record, @Param("example") DepartmentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByExample(@Param("record") Departmentinfo record, @Param("example") DepartmentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByPrimaryKeySelective(Departmentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmentinfo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByPrimaryKey(Departmentinfo record);
}