package com.giit.www.mapper;

import com.giit.www.entity.Freecutting;
import com.giit.www.entity.FreecuttingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreecuttingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int countByExample(FreecuttingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int deleteByExample(FreecuttingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int deleteByPrimaryKey(String cutnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int insert(Freecutting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int insertSelective(Freecutting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    List<Freecutting> selectByExample(FreecuttingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    Freecutting selectByPrimaryKey(String cutnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") Freecutting record, @Param("example") FreecuttingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int updateByExample(@Param("record") Freecutting record, @Param("example") FreecuttingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int updateByPrimaryKeySelective(Freecutting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecutting
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    int updateByPrimaryKey(Freecutting record);
}