package com.giit.www.mapper;

import com.giit.www.entity.Recordinformation;
import com.giit.www.entity.RecordinformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordinformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int countByExample(RecordinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int deleteByExample(RecordinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int deleteByPrimaryKey(String casenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int insert(Recordinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int insertSelective(Recordinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    List<Recordinformation> selectByExample(RecordinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    Recordinformation selectByPrimaryKey(String casenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") Recordinformation record, @Param("example") RecordinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByExample(@Param("record") Recordinformation record, @Param("example") RecordinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByPrimaryKeySelective(Recordinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recordinformation
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    int updateByPrimaryKey(Recordinformation record);

    List<Recordinformation> findAll();
}