package com.giit.www.entity;

import java.util.Date;

public class BussinessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.Bunumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String bunumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.CaseNumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String casenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuSTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private Date bustime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuOTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private Date buotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuPName
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String bupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuPDesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String bupdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuODesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String buodesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.BuPupload
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String bupupload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bussiness_info.Isend
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    private String isend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.Bunumber
     *
     * @return the value of bussiness_info.Bunumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getBunumber() {
        return bunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.Bunumber
     *
     * @param bunumber the value for bussiness_info.Bunumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBunumber(String bunumber) {
        this.bunumber = bunumber == null ? null : bunumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.CaseNumber
     *
     * @return the value of bussiness_info.CaseNumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getCasenumber() {
        return casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.CaseNumber
     *
     * @param casenumber the value for bussiness_info.CaseNumber
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setCasenumber(String casenumber) {
        this.casenumber = casenumber == null ? null : casenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuSTime
     *
     * @return the value of bussiness_info.BuSTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public Date getBustime() {
        return bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuSTime
     *
     * @param bustime the value for bussiness_info.BuSTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBustime(Date bustime) {
        this.bustime = bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuOTime
     *
     * @return the value of bussiness_info.BuOTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public Date getBuotime() {
        return buotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuOTime
     *
     * @param buotime the value for bussiness_info.BuOTime
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBuotime(Date buotime) {
        this.buotime = buotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuPName
     *
     * @return the value of bussiness_info.BuPName
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getBupname() {
        return bupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuPName
     *
     * @param bupname the value for bussiness_info.BuPName
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBupname(String bupname) {
        this.bupname = bupname == null ? null : bupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuPDesc
     *
     * @return the value of bussiness_info.BuPDesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getBupdesc() {
        return bupdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuPDesc
     *
     * @param bupdesc the value for bussiness_info.BuPDesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBupdesc(String bupdesc) {
        this.bupdesc = bupdesc == null ? null : bupdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuODesc
     *
     * @return the value of bussiness_info.BuODesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getBuodesc() {
        return buodesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuODesc
     *
     * @param buodesc the value for bussiness_info.BuODesc
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBuodesc(String buodesc) {
        this.buodesc = buodesc == null ? null : buodesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.BuPupload
     *
     * @return the value of bussiness_info.BuPupload
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getBupupload() {
        return bupupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.BuPupload
     *
     * @param bupupload the value for bussiness_info.BuPupload
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setBupupload(String bupupload) {
        this.bupupload = bupupload == null ? null : bupupload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bussiness_info.Isend
     *
     * @return the value of bussiness_info.Isend
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public String getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bussiness_info.Isend
     *
     * @param isend the value for bussiness_info.Isend
     *
     * @mbggenerated Sat Jul 01 19:02:56 CST 2017
     */
    public void setIsend(String isend) {
        this.isend = isend == null ? null : isend.trim();
    }
}