package com.giit.www.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileinfosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public FileinfosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileidIsNull() {
            addCriterion("Fileid is null");
            return (Criteria) this;
        }

        public Criteria andFileidIsNotNull() {
            addCriterion("Fileid is not null");
            return (Criteria) this;
        }

        public Criteria andFileidEqualTo(String value) {
            addCriterion("Fileid =", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotEqualTo(String value) {
            addCriterion("Fileid <>", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThan(String value) {
            addCriterion("Fileid >", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThanOrEqualTo(String value) {
            addCriterion("Fileid >=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThan(String value) {
            addCriterion("Fileid <", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThanOrEqualTo(String value) {
            addCriterion("Fileid <=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLike(String value) {
            addCriterion("Fileid like", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotLike(String value) {
            addCriterion("Fileid not like", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidIn(List<String> values) {
            addCriterion("Fileid in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotIn(List<String> values) {
            addCriterion("Fileid not in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidBetween(String value1, String value2) {
            addCriterion("Fileid between", value1, value2, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotBetween(String value1, String value2) {
            addCriterion("Fileid not between", value1, value2, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileonameIsNull() {
            addCriterion("FileOname is null");
            return (Criteria) this;
        }

        public Criteria andFileonameIsNotNull() {
            addCriterion("FileOname is not null");
            return (Criteria) this;
        }

        public Criteria andFileonameEqualTo(String value) {
            addCriterion("FileOname =", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameNotEqualTo(String value) {
            addCriterion("FileOname <>", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameGreaterThan(String value) {
            addCriterion("FileOname >", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameGreaterThanOrEqualTo(String value) {
            addCriterion("FileOname >=", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameLessThan(String value) {
            addCriterion("FileOname <", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameLessThanOrEqualTo(String value) {
            addCriterion("FileOname <=", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameLike(String value) {
            addCriterion("FileOname like", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameNotLike(String value) {
            addCriterion("FileOname not like", value, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameIn(List<String> values) {
            addCriterion("FileOname in", values, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameNotIn(List<String> values) {
            addCriterion("FileOname not in", values, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameBetween(String value1, String value2) {
            addCriterion("FileOname between", value1, value2, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFileonameNotBetween(String value1, String value2) {
            addCriterion("FileOname not between", value1, value2, "fileoname");
            return (Criteria) this;
        }

        public Criteria andFilennameIsNull() {
            addCriterion("FileNname is null");
            return (Criteria) this;
        }

        public Criteria andFilennameIsNotNull() {
            addCriterion("FileNname is not null");
            return (Criteria) this;
        }

        public Criteria andFilennameEqualTo(String value) {
            addCriterion("FileNname =", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameNotEqualTo(String value) {
            addCriterion("FileNname <>", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameGreaterThan(String value) {
            addCriterion("FileNname >", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameGreaterThanOrEqualTo(String value) {
            addCriterion("FileNname >=", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameLessThan(String value) {
            addCriterion("FileNname <", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameLessThanOrEqualTo(String value) {
            addCriterion("FileNname <=", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameLike(String value) {
            addCriterion("FileNname like", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameNotLike(String value) {
            addCriterion("FileNname not like", value, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameIn(List<String> values) {
            addCriterion("FileNname in", values, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameNotIn(List<String> values) {
            addCriterion("FileNname not in", values, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameBetween(String value1, String value2) {
            addCriterion("FileNname between", value1, value2, "filenname");
            return (Criteria) this;
        }

        public Criteria andFilennameNotBetween(String value1, String value2) {
            addCriterion("FileNname not between", value1, value2, "filenname");
            return (Criteria) this;
        }

        public Criteria andFileenameIsNull() {
            addCriterion("FileEname is null");
            return (Criteria) this;
        }

        public Criteria andFileenameIsNotNull() {
            addCriterion("FileEname is not null");
            return (Criteria) this;
        }

        public Criteria andFileenameEqualTo(String value) {
            addCriterion("FileEname =", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameNotEqualTo(String value) {
            addCriterion("FileEname <>", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameGreaterThan(String value) {
            addCriterion("FileEname >", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameGreaterThanOrEqualTo(String value) {
            addCriterion("FileEname >=", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameLessThan(String value) {
            addCriterion("FileEname <", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameLessThanOrEqualTo(String value) {
            addCriterion("FileEname <=", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameLike(String value) {
            addCriterion("FileEname like", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameNotLike(String value) {
            addCriterion("FileEname not like", value, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameIn(List<String> values) {
            addCriterion("FileEname in", values, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameNotIn(List<String> values) {
            addCriterion("FileEname not in", values, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameBetween(String value1, String value2) {
            addCriterion("FileEname between", value1, value2, "fileename");
            return (Criteria) this;
        }

        public Criteria andFileenameNotBetween(String value1, String value2) {
            addCriterion("FileEname not between", value1, value2, "fileename");
            return (Criteria) this;
        }

        public Criteria andFiletimeIsNull() {
            addCriterion("Filetime is null");
            return (Criteria) this;
        }

        public Criteria andFiletimeIsNotNull() {
            addCriterion("Filetime is not null");
            return (Criteria) this;
        }

        public Criteria andFiletimeEqualTo(Date value) {
            addCriterion("Filetime =", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeNotEqualTo(Date value) {
            addCriterion("Filetime <>", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeGreaterThan(Date value) {
            addCriterion("Filetime >", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Filetime >=", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeLessThan(Date value) {
            addCriterion("Filetime <", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeLessThanOrEqualTo(Date value) {
            addCriterion("Filetime <=", value, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeIn(List<Date> values) {
            addCriterion("Filetime in", values, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeNotIn(List<Date> values) {
            addCriterion("Filetime not in", values, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeBetween(Date value1, Date value2) {
            addCriterion("Filetime between", value1, value2, "filetime");
            return (Criteria) this;
        }

        public Criteria andFiletimeNotBetween(Date value1, Date value2) {
            addCriterion("Filetime not between", value1, value2, "filetime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileinfos
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 02 13:07:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileinfos
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}