package com.giit.www.entity;

public class Freecutting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecutting.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cutnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecutting.Cutname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cutname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecutting.CutExpress
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cutexpress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecutting.IlligalDesc
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String illigaldesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecutting.Cutnumber
     *
     * @return the value of freecutting.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCutnumber() {
        return cutnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecutting.Cutnumber
     *
     * @param cutnumber the value for freecutting.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCutnumber(String cutnumber) {
        this.cutnumber = cutnumber == null ? null : cutnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecutting.Cutname
     *
     * @return the value of freecutting.Cutname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCutname() {
        return cutname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecutting.Cutname
     *
     * @param cutname the value for freecutting.Cutname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCutname(String cutname) {
        this.cutname = cutname == null ? null : cutname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecutting.CutExpress
     *
     * @return the value of freecutting.CutExpress
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCutexpress() {
        return cutexpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecutting.CutExpress
     *
     * @param cutexpress the value for freecutting.CutExpress
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCutexpress(String cutexpress) {
        this.cutexpress = cutexpress == null ? null : cutexpress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecutting.IlligalDesc
     *
     * @return the value of freecutting.IlligalDesc
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getIlligaldesc() {
        return illigaldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecutting.IlligalDesc
     *
     * @param illigaldesc the value for freecutting.IlligalDesc
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setIlligaldesc(String illigaldesc) {
        this.illigaldesc = illigaldesc == null ? null : illigaldesc.trim();
    }
}