package com.giit.www.entity;

public class Punishment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.Itemid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.Itemname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.Itemcate
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String itemcate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.punishtype
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String punishtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment.Punishstandard
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String punishstandard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.Itemid
     *
     * @return the value of punishment.Itemid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.Itemid
     *
     * @param itemid the value for punishment.Itemid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.Itemname
     *
     * @return the value of punishment.Itemname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.Itemname
     *
     * @param itemname the value for punishment.Itemname
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.Itemcate
     *
     * @return the value of punishment.Itemcate
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getItemcate() {
        return itemcate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.Itemcate
     *
     * @param itemcate the value for punishment.Itemcate
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setItemcate(String itemcate) {
        this.itemcate = itemcate == null ? null : itemcate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.Department
     *
     * @return the value of punishment.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.Department
     *
     * @param department the value for punishment.Department
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.punishtype
     *
     * @return the value of punishment.punishtype
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getPunishtype() {
        return punishtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.punishtype
     *
     * @param punishtype the value for punishment.punishtype
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setPunishtype(String punishtype) {
        this.punishtype = punishtype == null ? null : punishtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment.Punishstandard
     *
     * @return the value of punishment.Punishstandard
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getPunishstandard() {
        return punishstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment.Punishstandard
     *
     * @param punishstandard the value for punishment.Punishstandard
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setPunishstandard(String punishstandard) {
        this.punishstandard = punishstandard == null ? null : punishstandard.trim();
    }
}