package com.giit.www.entity;

import java.util.Date;

public class Recordinformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.CaseNumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String casenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Casetitle
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String casetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Parties
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String parties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Casesource
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String casesource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Casename
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String casename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Recordtime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Crimereports
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String crimereports;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.According
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String according;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Fileupload
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String fileupload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Casemold
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String casemold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String cutnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String dpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordinformation.CurrentstaUis
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    private String currentstauis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.CaseNumber
     *
     * @return the value of recordinformation.CaseNumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCasenumber() {
        return casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.CaseNumber
     *
     * @param casenumber the value for recordinformation.CaseNumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCasenumber(String casenumber) {
        this.casenumber = casenumber == null ? null : casenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Userid
     *
     * @return the value of recordinformation.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Userid
     *
     * @param userid the value for recordinformation.Userid
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Casetitle
     *
     * @return the value of recordinformation.Casetitle
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCasetitle() {
        return casetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Casetitle
     *
     * @param casetitle the value for recordinformation.Casetitle
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCasetitle(String casetitle) {
        this.casetitle = casetitle == null ? null : casetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Parties
     *
     * @return the value of recordinformation.Parties
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getParties() {
        return parties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Parties
     *
     * @param parties the value for recordinformation.Parties
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setParties(String parties) {
        this.parties = parties == null ? null : parties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Casesource
     *
     * @return the value of recordinformation.Casesource
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCasesource() {
        return casesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Casesource
     *
     * @param casesource the value for recordinformation.Casesource
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCasesource(String casesource) {
        this.casesource = casesource == null ? null : casesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Casename
     *
     * @return the value of recordinformation.Casename
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCasename() {
        return casename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Casename
     *
     * @param casename the value for recordinformation.Casename
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCasename(String casename) {
        this.casename = casename == null ? null : casename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Recordtime
     *
     * @return the value of recordinformation.Recordtime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Recordtime
     *
     * @param recordtime the value for recordinformation.Recordtime
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Crimereports
     *
     * @return the value of recordinformation.Crimereports
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCrimereports() {
        return crimereports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Crimereports
     *
     * @param crimereports the value for recordinformation.Crimereports
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCrimereports(String crimereports) {
        this.crimereports = crimereports == null ? null : crimereports.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.According
     *
     * @return the value of recordinformation.According
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getAccording() {
        return according;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.According
     *
     * @param according the value for recordinformation.According
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setAccording(String according) {
        this.according = according == null ? null : according.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Fileupload
     *
     * @return the value of recordinformation.Fileupload
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getFileupload() {
        return fileupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Fileupload
     *
     * @param fileupload the value for recordinformation.Fileupload
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setFileupload(String fileupload) {
        this.fileupload = fileupload == null ? null : fileupload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Casemold
     *
     * @return the value of recordinformation.Casemold
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCasemold() {
        return casemold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Casemold
     *
     * @param casemold the value for recordinformation.Casemold
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCasemold(String casemold) {
        this.casemold = casemold == null ? null : casemold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.Cutnumber
     *
     * @return the value of recordinformation.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCutnumber() {
        return cutnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.Cutnumber
     *
     * @param cutnumber the value for recordinformation.Cutnumber
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCutnumber(String cutnumber) {
        this.cutnumber = cutnumber == null ? null : cutnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.DpNo
     *
     * @return the value of recordinformation.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getDpno() {
        return dpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.DpNo
     *
     * @param dpno the value for recordinformation.DpNo
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setDpno(String dpno) {
        this.dpno = dpno == null ? null : dpno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordinformation.CurrentstaUis
     *
     * @return the value of recordinformation.CurrentstaUis
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public String getCurrentstauis() {
        return currentstauis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordinformation.CurrentstaUis
     *
     * @param currentstauis the value for recordinformation.CurrentstaUis
     *
     * @mbggenerated Thu Jul 06 22:59:22 CST 2017
     */
    public void setCurrentstauis(String currentstauis) {
        this.currentstauis = currentstauis == null ? null : currentstauis.trim();
    }
}