package com.giit.www.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServiceinformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public ServiceinformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBunumberIsNull() {
            addCriterion("BuNumber is null");
            return (Criteria) this;
        }

        public Criteria andBunumberIsNotNull() {
            addCriterion("BuNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBunumberEqualTo(String value) {
            addCriterion("BuNumber =", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberNotEqualTo(String value) {
            addCriterion("BuNumber <>", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberGreaterThan(String value) {
            addCriterion("BuNumber >", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberGreaterThanOrEqualTo(String value) {
            addCriterion("BuNumber >=", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberLessThan(String value) {
            addCriterion("BuNumber <", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberLessThanOrEqualTo(String value) {
            addCriterion("BuNumber <=", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberLike(String value) {
            addCriterion("BuNumber like", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberNotLike(String value) {
            addCriterion("BuNumber not like", value, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberIn(List<String> values) {
            addCriterion("BuNumber in", values, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberNotIn(List<String> values) {
            addCriterion("BuNumber not in", values, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberBetween(String value1, String value2) {
            addCriterion("BuNumber between", value1, value2, "bunumber");
            return (Criteria) this;
        }

        public Criteria andBunumberNotBetween(String value1, String value2) {
            addCriterion("BuNumber not between", value1, value2, "bunumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNull() {
            addCriterion("CaseNumber is null");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNotNull() {
            addCriterion("CaseNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCasenumberEqualTo(String value) {
            addCriterion("CaseNumber =", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotEqualTo(String value) {
            addCriterion("CaseNumber <>", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThan(String value) {
            addCriterion("CaseNumber >", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThanOrEqualTo(String value) {
            addCriterion("CaseNumber >=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThan(String value) {
            addCriterion("CaseNumber <", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThanOrEqualTo(String value) {
            addCriterion("CaseNumber <=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLike(String value) {
            addCriterion("CaseNumber like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotLike(String value) {
            addCriterion("CaseNumber not like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIn(List<String> values) {
            addCriterion("CaseNumber in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotIn(List<String> values) {
            addCriterion("CaseNumber not in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberBetween(String value1, String value2) {
            addCriterion("CaseNumber between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotBetween(String value1, String value2) {
            addCriterion("CaseNumber not between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andBustimeIsNull() {
            addCriterion("BuSTime is null");
            return (Criteria) this;
        }

        public Criteria andBustimeIsNotNull() {
            addCriterion("BuSTime is not null");
            return (Criteria) this;
        }

        public Criteria andBustimeEqualTo(Date value) {
            addCriterion("BuSTime =", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeNotEqualTo(Date value) {
            addCriterion("BuSTime <>", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeGreaterThan(Date value) {
            addCriterion("BuSTime >", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeGreaterThanOrEqualTo(Date value) {
            addCriterion("BuSTime >=", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeLessThan(Date value) {
            addCriterion("BuSTime <", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeLessThanOrEqualTo(Date value) {
            addCriterion("BuSTime <=", value, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeIn(List<Date> values) {
            addCriterion("BuSTime in", values, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeNotIn(List<Date> values) {
            addCriterion("BuSTime not in", values, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeBetween(Date value1, Date value2) {
            addCriterion("BuSTime between", value1, value2, "bustime");
            return (Criteria) this;
        }

        public Criteria andBustimeNotBetween(Date value1, Date value2) {
            addCriterion("BuSTime not between", value1, value2, "bustime");
            return (Criteria) this;
        }

        public Criteria andBuotimeIsNull() {
            addCriterion("BuOTime is null");
            return (Criteria) this;
        }

        public Criteria andBuotimeIsNotNull() {
            addCriterion("BuOTime is not null");
            return (Criteria) this;
        }

        public Criteria andBuotimeEqualTo(Date value) {
            addCriterion("BuOTime =", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeNotEqualTo(Date value) {
            addCriterion("BuOTime <>", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeGreaterThan(Date value) {
            addCriterion("BuOTime >", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeGreaterThanOrEqualTo(Date value) {
            addCriterion("BuOTime >=", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeLessThan(Date value) {
            addCriterion("BuOTime <", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeLessThanOrEqualTo(Date value) {
            addCriterion("BuOTime <=", value, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeIn(List<Date> values) {
            addCriterion("BuOTime in", values, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeNotIn(List<Date> values) {
            addCriterion("BuOTime not in", values, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeBetween(Date value1, Date value2) {
            addCriterion("BuOTime between", value1, value2, "buotime");
            return (Criteria) this;
        }

        public Criteria andBuotimeNotBetween(Date value1, Date value2) {
            addCriterion("BuOTime not between", value1, value2, "buotime");
            return (Criteria) this;
        }

        public Criteria andBupnameIsNull() {
            addCriterion("BuPName is null");
            return (Criteria) this;
        }

        public Criteria andBupnameIsNotNull() {
            addCriterion("BuPName is not null");
            return (Criteria) this;
        }

        public Criteria andBupnameEqualTo(String value) {
            addCriterion("BuPName =", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameNotEqualTo(String value) {
            addCriterion("BuPName <>", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameGreaterThan(String value) {
            addCriterion("BuPName >", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameGreaterThanOrEqualTo(String value) {
            addCriterion("BuPName >=", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameLessThan(String value) {
            addCriterion("BuPName <", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameLessThanOrEqualTo(String value) {
            addCriterion("BuPName <=", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameLike(String value) {
            addCriterion("BuPName like", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameNotLike(String value) {
            addCriterion("BuPName not like", value, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameIn(List<String> values) {
            addCriterion("BuPName in", values, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameNotIn(List<String> values) {
            addCriterion("BuPName not in", values, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameBetween(String value1, String value2) {
            addCriterion("BuPName between", value1, value2, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupnameNotBetween(String value1, String value2) {
            addCriterion("BuPName not between", value1, value2, "bupname");
            return (Criteria) this;
        }

        public Criteria andBupdescIsNull() {
            addCriterion("BuPDesc is null");
            return (Criteria) this;
        }

        public Criteria andBupdescIsNotNull() {
            addCriterion("BuPDesc is not null");
            return (Criteria) this;
        }

        public Criteria andBupdescEqualTo(String value) {
            addCriterion("BuPDesc =", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescNotEqualTo(String value) {
            addCriterion("BuPDesc <>", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescGreaterThan(String value) {
            addCriterion("BuPDesc >", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescGreaterThanOrEqualTo(String value) {
            addCriterion("BuPDesc >=", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescLessThan(String value) {
            addCriterion("BuPDesc <", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescLessThanOrEqualTo(String value) {
            addCriterion("BuPDesc <=", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescLike(String value) {
            addCriterion("BuPDesc like", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescNotLike(String value) {
            addCriterion("BuPDesc not like", value, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescIn(List<String> values) {
            addCriterion("BuPDesc in", values, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescNotIn(List<String> values) {
            addCriterion("BuPDesc not in", values, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescBetween(String value1, String value2) {
            addCriterion("BuPDesc between", value1, value2, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBupdescNotBetween(String value1, String value2) {
            addCriterion("BuPDesc not between", value1, value2, "bupdesc");
            return (Criteria) this;
        }

        public Criteria andBuodescIsNull() {
            addCriterion("BuODesc is null");
            return (Criteria) this;
        }

        public Criteria andBuodescIsNotNull() {
            addCriterion("BuODesc is not null");
            return (Criteria) this;
        }

        public Criteria andBuodescEqualTo(String value) {
            addCriterion("BuODesc =", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescNotEqualTo(String value) {
            addCriterion("BuODesc <>", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescGreaterThan(String value) {
            addCriterion("BuODesc >", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescGreaterThanOrEqualTo(String value) {
            addCriterion("BuODesc >=", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescLessThan(String value) {
            addCriterion("BuODesc <", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescLessThanOrEqualTo(String value) {
            addCriterion("BuODesc <=", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescLike(String value) {
            addCriterion("BuODesc like", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescNotLike(String value) {
            addCriterion("BuODesc not like", value, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescIn(List<String> values) {
            addCriterion("BuODesc in", values, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescNotIn(List<String> values) {
            addCriterion("BuODesc not in", values, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescBetween(String value1, String value2) {
            addCriterion("BuODesc between", value1, value2, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBuodescNotBetween(String value1, String value2) {
            addCriterion("BuODesc not between", value1, value2, "buodesc");
            return (Criteria) this;
        }

        public Criteria andBupuploadIsNull() {
            addCriterion("BuPupload is null");
            return (Criteria) this;
        }

        public Criteria andBupuploadIsNotNull() {
            addCriterion("BuPupload is not null");
            return (Criteria) this;
        }

        public Criteria andBupuploadEqualTo(String value) {
            addCriterion("BuPupload =", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadNotEqualTo(String value) {
            addCriterion("BuPupload <>", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadGreaterThan(String value) {
            addCriterion("BuPupload >", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadGreaterThanOrEqualTo(String value) {
            addCriterion("BuPupload >=", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadLessThan(String value) {
            addCriterion("BuPupload <", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadLessThanOrEqualTo(String value) {
            addCriterion("BuPupload <=", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadLike(String value) {
            addCriterion("BuPupload like", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadNotLike(String value) {
            addCriterion("BuPupload not like", value, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadIn(List<String> values) {
            addCriterion("BuPupload in", values, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadNotIn(List<String> values) {
            addCriterion("BuPupload not in", values, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadBetween(String value1, String value2) {
            addCriterion("BuPupload between", value1, value2, "bupupload");
            return (Criteria) this;
        }

        public Criteria andBupuploadNotBetween(String value1, String value2) {
            addCriterion("BuPupload not between", value1, value2, "bupupload");
            return (Criteria) this;
        }

        public Criteria andCasewhetherIsNull() {
            addCriterion("Casewhether is null");
            return (Criteria) this;
        }

        public Criteria andCasewhetherIsNotNull() {
            addCriterion("Casewhether is not null");
            return (Criteria) this;
        }

        public Criteria andCasewhetherEqualTo(String value) {
            addCriterion("Casewhether =", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherNotEqualTo(String value) {
            addCriterion("Casewhether <>", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherGreaterThan(String value) {
            addCriterion("Casewhether >", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherGreaterThanOrEqualTo(String value) {
            addCriterion("Casewhether >=", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherLessThan(String value) {
            addCriterion("Casewhether <", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherLessThanOrEqualTo(String value) {
            addCriterion("Casewhether <=", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherLike(String value) {
            addCriterion("Casewhether like", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherNotLike(String value) {
            addCriterion("Casewhether not like", value, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherIn(List<String> values) {
            addCriterion("Casewhether in", values, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherNotIn(List<String> values) {
            addCriterion("Casewhether not in", values, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherBetween(String value1, String value2) {
            addCriterion("Casewhether between", value1, value2, "casewhether");
            return (Criteria) this;
        }

        public Criteria andCasewhetherNotBetween(String value1, String value2) {
            addCriterion("Casewhether not between", value1, value2, "casewhether");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceinformation
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 09 18:41:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceinformation
     *
     * @mbggenerated Sun Jul 09 18:41:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}