package com.giit.www.entity;

import java.util.Date;

public class Serviceinformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String bunumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.CaseNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String casenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuSTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private Date bustime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuOTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private Date buotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuPName
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String bupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuPDesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String bupdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuODesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String buodesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.BuPupload
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String bupupload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serviceinformation.Casewhether
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    private String casewhether;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuNumber
     *
     * @return the value of serviceinformation.BuNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getBunumber() {
        return bunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuNumber
     *
     * @param bunumber the value for serviceinformation.BuNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBunumber(String bunumber) {
        this.bunumber = bunumber == null ? null : bunumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.CaseNumber
     *
     * @return the value of serviceinformation.CaseNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getCasenumber() {
        return casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.CaseNumber
     *
     * @param casenumber the value for serviceinformation.CaseNumber
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setCasenumber(String casenumber) {
        this.casenumber = casenumber == null ? null : casenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuSTime
     *
     * @return the value of serviceinformation.BuSTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public Date getBustime() {
        return bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuSTime
     *
     * @param bustime the value for serviceinformation.BuSTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBustime(Date bustime) {
        this.bustime = bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuOTime
     *
     * @return the value of serviceinformation.BuOTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public Date getBuotime() {
        return buotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuOTime
     *
     * @param buotime the value for serviceinformation.BuOTime
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBuotime(Date buotime) {
        this.buotime = buotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuPName
     *
     * @return the value of serviceinformation.BuPName
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getBupname() {
        return bupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuPName
     *
     * @param bupname the value for serviceinformation.BuPName
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBupname(String bupname) {
        this.bupname = bupname == null ? null : bupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuPDesc
     *
     * @return the value of serviceinformation.BuPDesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getBupdesc() {
        return bupdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuPDesc
     *
     * @param bupdesc the value for serviceinformation.BuPDesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBupdesc(String bupdesc) {
        this.bupdesc = bupdesc == null ? null : bupdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuODesc
     *
     * @return the value of serviceinformation.BuODesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getBuodesc() {
        return buodesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuODesc
     *
     * @param buodesc the value for serviceinformation.BuODesc
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBuodesc(String buodesc) {
        this.buodesc = buodesc == null ? null : buodesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.BuPupload
     *
     * @return the value of serviceinformation.BuPupload
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getBupupload() {
        return bupupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.BuPupload
     *
     * @param bupupload the value for serviceinformation.BuPupload
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setBupupload(String bupupload) {
        this.bupupload = bupupload == null ? null : bupupload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column serviceinformation.Casewhether
     *
     * @return the value of serviceinformation.Casewhether
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public String getCasewhether() {
        return casewhether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column serviceinformation.Casewhether
     *
     * @param casewhether the value for serviceinformation.Casewhether
     *
     * @mbggenerated Sun Jul 02 13:07:31 CST 2017
     */
    public void setCasewhether(String casewhether) {
        this.casewhether = casewhether == null ? null : casewhether.trim();
    }
}